// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzwjzwbbriqrgppkbtdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6d2p6d2JicmlxcmdwcGtidGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTYyOTcsImV4cCI6MjA2MzIzMjI5N30.--qroL25aURh5KBkfbfuH93zAA1sD3oI-u1SNeeRjyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);